/* eslint-disable */
// AUTO-GENERATED by scripts/convert-travel-csv.mjs — do not edit by hand.
// Re-export sheet CSV from src/data/raw/ and run: npm run travel:import

export const generatedTravelUnits = {
  "holiday-ha-long": {
    "unitSamples": [
      {
        "code": "1005",
        "unitType": "Studio View phố",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "1006",
        "unitType": "Studio View phố",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "2917",
        "unitType": "Studio View bể bơi",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "H15A01",
        "unitType": "Studio View bể bơi",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "12A16",
        "unitType": "Studio View bể bơi",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "2805A",
        "unitType": "Studio View phố",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "15A05",
        "unitType": "Studio View phố",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "2506",
        "unitType": "Studio View phố",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "3106",
        "unitType": "Studio View phố",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "15A03",
        "unitType": "Studio View phố",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "1215",
        "unitType": "Studio View Biển",
        "weekdayPrice": "800.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "2416",
        "unitType": "Studio View phố",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "0915",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.000.000đ/đêm",
        "weekendPrice": "1.200.000đ/đêm"
      },
      {
        "code": "3315a",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.000.000đ/đêm",
        "weekendPrice": "1.200.000đ/đêm"
      },
      {
        "code": "2615a",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.000.000đ/đêm",
        "weekendPrice": "1.200.000đ/đêm"
      },
      {
        "code": "2611",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "2510",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "2512a",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "2815",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "1511",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "1810",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "2010",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "2310",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "3015A",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "2715A",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "2715",
        "unitType": "Studio View Biển",
        "weekdayPrice": "1.100.000đ/đêm",
        "weekendPrice": "1.300.000đ/đêm"
      },
      {
        "code": "2701",
        "unitType": "Studio View Bể Bơi",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "3405A",
        "unitType": "Studio View Đà Lạt",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "3502",
        "unitType": "Studio View Đà Lạt",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "1.100.000đ/đêm"
      },
      {
        "code": "1109",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "0909",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "1108",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "2109",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "2509",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "3108",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "3209",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "3308",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "3309",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "3508",
        "unitType": "2 Ngủ View biển",
        "weekdayPrice": "1.800.000đ/đêm",
        "weekendPrice": "2.300.000đ/đêm"
      },
      {
        "code": "A1802",
        "unitType": "Bim 30 tầng",
        "weekdayPrice": "900.000đ/đêm",
        "weekendPrice": "2.500.000đ/2Đ"
      }
    ],
    "priceSummary": [
      {
        "label": "Studio View phố",
        "weekday": "Từ 900.000đ/đêm",
        "weekend": "Từ 1.100.000đ/đêm",
        "note": "Giá tham khảo từ sheet Holiday Hạ Long"
      },
      {
        "label": "Studio View bể bơi",
        "weekday": "Từ 900.000đ/đêm",
        "weekend": "Từ 1.100.000đ/đêm",
        "note": "Giá tham khảo từ sheet Holiday Hạ Long"
      },
      {
        "label": "Studio View Biển",
        "weekday": "Từ 800.000đ/đêm",
        "weekend": "Từ 1.100.000đ/đêm",
        "note": "Giá tham khảo từ sheet Holiday Hạ Long"
      },
      {
        "label": "Studio View Bể Bơi",
        "weekday": "Từ 900.000đ/đêm",
        "weekend": "Từ 1.100.000đ/đêm",
        "note": "Giá tham khảo từ sheet Holiday Hạ Long"
      },
      {
        "label": "Studio View Đà Lạt",
        "weekday": "Từ 900.000đ/đêm",
        "weekend": "Từ 1.100.000đ/đêm",
        "note": "Giá tham khảo từ sheet Holiday Hạ Long"
      },
      {
        "label": "2 Ngủ View biển",
        "weekday": "Từ 1.800.000đ/đêm",
        "weekend": "Từ 2.300.000đ/đêm",
        "note": "Giá tham khảo từ sheet Holiday Hạ Long"
      },
      {
        "label": "Bim 30 tầng",
        "weekday": "Từ 900.000đ/đêm",
        "note": "Giá tham khảo từ sheet Holiday Hạ Long"
      }
    ],
    "unitTypeGroups": [
      {
        "name": "2 Ngủ View biển",
        "description": "Có trong quỹ Holiday Hạ Long — liên hệ DST để check mã 2 Ngủ View biển còn trống."
      },
      {
        "name": "Bim 30 tầng",
        "description": "Có trong quỹ Holiday Hạ Long — liên hệ DST để check mã Bim 30 tầng còn trống."
      },
      {
        "name": "Studio View bể bơi",
        "description": "Có trong quỹ Holiday Hạ Long — liên hệ DST để check mã Studio View bể bơi còn trống."
      },
      {
        "name": "Studio View Bể Bơi",
        "description": "Có trong quỹ Holiday Hạ Long — liên hệ DST để check mã Studio View Bể Bơi còn trống."
      },
      {
        "name": "Studio View Biển",
        "description": "Có trong quỹ Holiday Hạ Long — liên hệ DST để check mã Studio View Biển còn trống."
      },
      {
        "name": "Studio View Đà Lạt",
        "description": "Có trong quỹ Holiday Hạ Long — liên hệ DST để check mã Studio View Đà Lạt còn trống."
      },
      {
        "name": "Studio View phố",
        "description": "Có trong quỹ Holiday Hạ Long — liên hệ DST để check mã Studio View phố còn trống."
      }
    ],
    "amenities": [
      "Studio View phố",
      "Studio View bể bơi",
      "Studio View Biển",
      "Studio View Bể Bơi",
      "Studio View Đà Lạt",
      "2 Ngủ View biển",
      "Bim 30 tầng"
    ],
    "highlights": [
      "40 mã căn trong quỹ Holiday Hạ Long (sheet tháng 7/2026)",
      "Loại căn: Studio view phố, view biển, view bể bơi, 2 ngủ view biển",
      "Giá ngày thường và cuối tuần (T6–T7, T7–CN) khác nhau theo từng mã căn",
      "DST hỗ trợ check lịch trống và báo giá theo ngày cụ thể"
    ],
    "dataSource": "Google Sheet Holiday Hạ Long — export CSV tháng 7/2026",
    "unitCount": 40
  },
  "villa-tuan-chau": {
    "unitSamples": [
      {
        "code": "Kingly",
        "bedrooms": 15,
        "features": [
          "Mặt biển, 1000m2, bàn bi a"
        ],
        "weekdayPrice": "18tr",
        "sundayPrice": "22tr",
        "fridayPrice": "22tr",
        "saturdayPrice": "26tr"
      },
      {
        "code": "The princess",
        "bedrooms": 9,
        "features": [
          "View panorama, Bàn Bi a"
        ],
        "weekdayPrice": "15 triệu/đêm",
        "sundayPrice": "15 triệu/đêm",
        "fridayPrice": "20tr",
        "saturdayPrice": "20tr ( bán cặp lẻ inbox)"
      },
      {
        "code": "Tahaghi",
        "bedrooms": 9,
        "features": [
          "Mặt biển, sân vườn tuyệt đẹp,1700m2"
        ],
        "weekdayPrice": "20 triệu/đêm",
        "sundayPrice": "20 triệu/đêm",
        "fridayPrice": "26.5 triệu/đêm",
        "saturdayPrice": "30 triệu/đêm"
      },
      {
        "code": "Santorini",
        "bedrooms": 5,
        "features": [
          "Kiến trúc độc đáo, view panorama"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "sundayPrice": "6.5 tr",
        "fridayPrice": "6.5tr"
      },
      {
        "code": "Calmaria",
        "bedrooms": 10,
        "features": [
          "Sân vườn rộng, sân bóng rổ, xe đạp, vườn rau,..."
        ],
        "weekdayPrice": "13.36 triệu/đêm",
        "sundayPrice": "15tr",
        "fridayPrice": "17.76 triệu/đêm",
        "saturdayPrice": "17.76 triệu/đêm"
      },
      {
        "code": "Green Field",
        "bedrooms": 10,
        "features": [
          "View Panaroma, Sân vườn 1000m2"
        ],
        "weekdayPrice": "16 triệu/đêm",
        "sundayPrice": "18 triệu/đêm",
        "fridayPrice": "40tr/ 2 đêm lẻ inbox"
      },
      {
        "code": "B01 Villa",
        "bedrooms": 7,
        "features": [
          "View Panaroma, Sân vườn rộng"
        ],
        "weekdayPrice": "8 triệu/đêm",
        "sundayPrice": "8 triệu/đêm",
        "fridayPrice": "24tr/2đ Lẻ thứ 7 15tr"
      }
    ],
    "priceSummary": [
      {
        "label": "10 PN",
        "weekday": "Từ 13.36–16 triệu/đêm",
        "friday": "Từ 17.76 triệu/đêm",
        "saturday": "Từ 17.76 triệu/đêm",
        "sunday": "Từ 18 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Tuần Châu"
      },
      {
        "label": "15 PN",
        "note": "Giá tham khảo từ sheet Villa Tuần Châu"
      },
      {
        "label": "5 PN",
        "weekday": "Từ 6.5 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Tuần Châu"
      },
      {
        "label": "7 PN",
        "weekday": "Từ 8 triệu/đêm",
        "sunday": "Từ 8 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Tuần Châu"
      },
      {
        "label": "9 PN",
        "weekday": "Từ 15–20 triệu/đêm",
        "friday": "Từ 26.5 triệu/đêm",
        "saturday": "Từ 30 triệu/đêm",
        "sunday": "Từ 15–20 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Tuần Châu"
      }
    ],
    "amenities": [
      "Mặt biển",
      "1000m2",
      "bàn bi a",
      "View panorama",
      "Bàn Bi a",
      "sân vườn tuyệt đẹp",
      "1700m2",
      "Kiến trúc độc đáo",
      "view panorama",
      "Sân vườn rộng",
      "sân bóng rổ",
      "xe đạp"
    ],
    "highlights": [
      "7 villa tiêu biểu tại Tuần Châu (dữ liệu sheet tháng 7/2026)",
      "Tiện ích thực tế: mặt biển, view panorama, sân vườn, bàn bi-a",
      "Giá theo ngày thường, thứ 6, thứ 7 và chủ nhật — một số căn bán cặp cuối tuần",
      "Nhấn liên hệ DST để xem ảnh và thông tin chi tiết từng villa"
    ],
    "dataSource": "Google Sheet Villa Tuần Châu — export CSV tháng 7/2026",
    "unitCount": 7
  },
  "villa-sun-feria": {
    "unitSamples": [
      {
        "code": "M6-33",
        "bedrooms": 7,
        "features": [
          "Gần bãi biển, Bể bơi rộng"
        ],
        "elevator": true,
        "weekdayPrice": "9 triệu/đêm",
        "sundayPrice": "9 triệu/đêm",
        "fridayPrice": "26tr/2đ"
      },
      {
        "code": "C7-21",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "7 triệu/đêm",
        "sundayPrice": "8 triệu/đêm",
        "fridayPrice": "23tr/2đ"
      },
      {
        "code": "C6-12",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "7 triệu/đêm",
        "sundayPrice": "8 triệu/đêm",
        "fridayPrice": "23tr/2đ"
      },
      {
        "code": "M5-37",
        "bedrooms": 7,
        "features": [
          "Bể bơi riêng, mới nhất Sun"
        ],
        "elevator": true,
        "weekdayPrice": "9 triệu/đêm",
        "sundayPrice": "11 triệu/đêm",
        "fridayPrice": "28tr/2đ"
      },
      {
        "code": "M2-12",
        "bedrooms": 8,
        "features": [
          "Bể bơi riêng, Bàn Bi-A mới hoạt động 3/2026"
        ],
        "elevator": true,
        "weekdayPrice": "11 triệu/đêm",
        "sundayPrice": "13 triệu/đêm",
        "fridayPrice": "34tr/2đ"
      },
      {
        "code": "C5-19",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "25tr/2đ"
      },
      {
        "code": "M6-42",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng, dàn karaoke, bàn Bi a"
        ],
        "elevator": false,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "9.5 triệu/đêm",
        "fridayPrice": "24tr/2đ"
      },
      {
        "code": "C2-18",
        "bedrooms": 5,
        "features": [
          "2 Bể bơi riêng, Nội thất chill"
        ],
        "elevator": false,
        "weekdayPrice": "9 triệu/đêm",
        "sundayPrice": "11 triệu/đêm",
        "fridayPrice": "25tr/2đ"
      },
      {
        "code": "C7-28",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng, view biển"
        ],
        "elevator": false,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "8.5 triệu/đêm",
        "fridayPrice": "25tr/2đ"
      },
      {
        "code": "C6-25",
        "bedrooms": 6,
        "features": [
          "Bể Bơi riêng, bàn Bi-A"
        ],
        "elevator": true,
        "weekdayPrice": "8 triệu/đêm",
        "sundayPrice": "9 triệu/đêm",
        "fridayPrice": "25tr/2đ"
      },
      {
        "code": "M2-36",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng- bàn bi a"
        ],
        "elevator": false,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "27tr/2đ"
      },
      {
        "code": "M2-30",
        "bedrooms": 8,
        "features": [
          "Bể Bơi riêng, bàn Bi-A"
        ],
        "elevator": true,
        "weekdayPrice": "13 triệu/đêm",
        "sundayPrice": "14 triệu/đêm",
        "fridayPrice": "38tr/ 2 đêm"
      },
      {
        "code": "M5-36",
        "bedrooms": 9,
        "features": [
          "Bể bơi riêng, Bàn Bi a"
        ],
        "elevator": false,
        "weekdayPrice": "13 triệu/đêm",
        "sundayPrice": "14 triệu/đêm",
        "fridayPrice": "38tr/2đ"
      },
      {
        "code": "M3-21",
        "bedrooms": 8,
        "features": [
          "Bể bơi riêng, Siêu vip"
        ],
        "elevator": false,
        "weekdayPrice": "16 triệu/đêm",
        "sundayPrice": "16 triệu/đêm",
        "fridayPrice": "38tr/2đ"
      },
      {
        "code": "C1-28 VIP",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng- bàn Bi A-saunaVIP"
        ],
        "elevator": true,
        "weekdayPrice": "9 triệu/đêm",
        "sundayPrice": "11 triệu/đêm",
        "fridayPrice": "28tr/2đ"
      },
      {
        "code": "C3-01",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng- Bi a"
        ],
        "elevator": false,
        "weekdayPrice": "7.5 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "23tr/2đ"
      },
      {
        "code": "C5-09",
        "bedrooms": 5,
        "features": [
          "Bể Bơi riêng"
        ],
        "elevator": true,
        "weekdayPrice": "7.5 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "23tr/2đ"
      },
      {
        "code": "M6-24",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng, Phòng Karaoke, bàn bi a"
        ],
        "elevator": true,
        "weekdayPrice": "9 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "25tr/2đ"
      },
      {
        "code": "C6-15",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "8 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "23tr/2đ"
      },
      {
        "code": "C1-26",
        "bedrooms": 6,
        "features": [
          "Bể Bơi riêng, bàn Bi-A"
        ],
        "elevator": false,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "24tr/2đ"
      },
      {
        "code": "M2-41",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng, View biển"
        ],
        "elevator": false,
        "weekdayPrice": "8 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "24tr/2đ"
      },
      {
        "code": "M3-34",
        "bedrooms": 7,
        "features": [
          "Bể bơi riêng, Dàn karaoke, Bi a"
        ],
        "elevator": false,
        "weekdayPrice": "9 triệu/đêm",
        "sundayPrice": "11 triệu/đêm",
        "fridayPrice": "26tr/2đ"
      },
      {
        "code": "C6-22",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "24tr/2đ"
      },
      {
        "code": "C7-10",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "7 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "24tr/2đ"
      },
      {
        "code": "TH703",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "6.5 triệu/đêm",
        "sundayPrice": "7.5 triệu/đêm",
        "fridayPrice": "22tr/2đ"
      },
      {
        "code": "TH709",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "7 triệu/đêm",
        "sundayPrice": "9 triệu/đêm",
        "fridayPrice": "10 triệu/đêm",
        "saturdayPrice": "11 triệu/đêm"
      },
      {
        "code": "M5-22",
        "bedrooms": 7,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": true,
        "weekdayPrice": "10 triệu/đêm",
        "sundayPrice": "12 triệu/đêm",
        "fridayPrice": "30 tr/ 2 đ"
      },
      {
        "code": "M1-01",
        "bedrooms": 8,
        "features": [
          "Bể Bơi riêng, bàn Bi-A"
        ],
        "elevator": true,
        "weekdayPrice": "11 triệu/đêm",
        "sundayPrice": "13 triệu/đêm",
        "fridayPrice": "34tr/2đ"
      },
      {
        "code": "M5-21",
        "bedrooms": 11,
        "features": [
          "Bể Bơi riêng, bàn Bi-A"
        ],
        "elevator": true,
        "weekdayPrice": "19 triệu/đêm",
        "sundayPrice": "21 triệu/đêm",
        "fridayPrice": "52tr/2đ"
      },
      {
        "code": "C2-29",
        "bedrooms": 12,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": true,
        "weekdayPrice": "17 triệu/đêm",
        "sundayPrice": "20 triệu/đêm",
        "fridayPrice": "52tr/2đ"
      },
      {
        "code": "M5-38",
        "bedrooms": 7,
        "features": [
          "Bể bơi riêng, Bàn Bi a"
        ],
        "elevator": true,
        "weekdayPrice": "12 triệu/đêm",
        "sundayPrice": "13 triệu/đêm",
        "fridayPrice": "32 tr/ 2 đ"
      },
      {
        "code": "C3-31",
        "bedrooms": 6,
        "features": [
          "Bể Bơi riêng, bàn Bi-A"
        ],
        "elevator": false,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "8.5 triệu/đêm",
        "fridayPrice": "26tr/2đ"
      },
      {
        "code": "C5-31",
        "bedrooms": 5,
        "features": [
          "Bể Bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "8 triệu/đêm",
        "sundayPrice": "8 triệu/đêm",
        "fridayPrice": "25tr/2đ"
      },
      {
        "code": "C5-32",
        "bedrooms": 5,
        "features": [
          "Bể Bơi riêng"
        ],
        "elevator": false,
        "weekdayPrice": "8 triệu/đêm",
        "sundayPrice": "8 triệu/đêm",
        "fridayPrice": "25tr/2đ"
      },
      {
        "code": "C2-19",
        "bedrooms": 7,
        "features": [
          "Bể bơi riêng"
        ],
        "elevator": true,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "8.5 triệu/đêm",
        "fridayPrice": "26tr/2đ"
      },
      {
        "code": "C8-06",
        "bedrooms": 7,
        "features": [
          "Bể Bơi riêng, bàn Bi-A"
        ],
        "elevator": true,
        "weekdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "9 triệu/đêm",
        "fridayPrice": "26tr/2đ"
      },
      {
        "code": "C6-33",
        "bedrooms": 7,
        "features": [
          "Bể bơi riêng, mặt biển"
        ],
        "elevator": true,
        "weekdayPrice": "14 triệu/đêm",
        "sundayPrice": "14 triệu/đêm",
        "fridayPrice": "36tr/2đ"
      },
      {
        "code": "C7-07",
        "bedrooms": 7,
        "features": [
          "Bể Bơi riêng, bàn Bi-A, dàn Karaoke"
        ],
        "elevator": true,
        "weekdayPrice": "13 triệu/đêm",
        "sundayPrice": "13 triệu/đêm",
        "fridayPrice": "34tr/2đ"
      },
      {
        "code": "C6-05",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng, bàn bilac"
        ],
        "elevator": true,
        "weekdayPrice": "7.5 triệu/đêm",
        "sundayPrice": "8.5 triệu/đêm",
        "fridayPrice": "23tr/2đ"
      },
      {
        "code": "M6-11",
        "bedrooms": 5,
        "features": [
          "Bể Bơi riêng, bàn Bi-A"
        ],
        "elevator": true,
        "weekdayPrice": "9.5 triệu/đêm",
        "sundayPrice": "12.5 triệu/đêm",
        "fridayPrice": "25tr/2đ"
      },
      {
        "code": "MYAN",
        "bedrooms": 6,
        "features": [
          "Bể bơi riêng, bàn bi a, sân vườn, cầu trượt"
        ],
        "elevator": false,
        "weekdayPrice": "11 triệu/đêm",
        "sundayPrice": "11 triệu/đêm",
        "fridayPrice": "14 triệu/đêm",
        "saturdayPrice": "14 triệu/đêm"
      },
      {
        "code": "Sun And Sea",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng, sân vườn, sát bãi tắm"
        ],
        "elevator": false,
        "weekdayPrice": "10 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "15 triệu/đêm",
        "saturdayPrice": "15 triệu/đêm"
      },
      {
        "code": "Mon R80",
        "bedrooms": 5,
        "features": [
          "Bể bơi riêng, sân vườn, sát bãi tắm"
        ],
        "weekdayPrice": "10 triệu/đêm",
        "sundayPrice": "10 triệu/đêm",
        "fridayPrice": "14 triệu/đêm",
        "saturdayPrice": "14 triệu/đêm"
      }
    ],
    "priceSummary": [
      {
        "label": "11 PN",
        "weekday": "Từ 19 triệu/đêm",
        "sunday": "Từ 21 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Sun Feria"
      },
      {
        "label": "12 PN",
        "weekday": "Từ 17 triệu/đêm",
        "sunday": "Từ 20 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Sun Feria"
      },
      {
        "label": "5 PN",
        "weekday": "Từ 6.5–10 triệu/đêm",
        "friday": "Từ 14–15 triệu/đêm",
        "saturday": "Từ 14–15 triệu/đêm",
        "sunday": "Từ 7.5–12.5 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Sun Feria"
      },
      {
        "label": "6 PN",
        "weekday": "Từ 7–11 triệu/đêm",
        "friday": "Từ 10–14 triệu/đêm",
        "saturday": "Từ 11–14 triệu/đêm",
        "sunday": "Từ 8.5–11 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Sun Feria"
      },
      {
        "label": "7 PN",
        "weekday": "Từ 8.5–14 triệu/đêm",
        "sunday": "Từ 8.5–14 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Sun Feria"
      },
      {
        "label": "8 PN",
        "weekday": "Từ 11–16 triệu/đêm",
        "sunday": "Từ 13–16 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Sun Feria"
      },
      {
        "label": "9 PN",
        "weekday": "Từ 13 triệu/đêm",
        "sunday": "Từ 14 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa Sun Feria"
      }
    ],
    "amenities": [
      "Gần bãi biển",
      "Bể bơi rộng",
      "Bể bơi riêng",
      "mới nhất Sun",
      "Bàn Bi-A mới hoạt động 3/2026",
      "dàn karaoke",
      "bàn Bi a",
      "2 Bể bơi riêng",
      "Nội thất chill",
      "view biển",
      "Bể Bơi riêng",
      "bàn Bi-A"
    ],
    "highlights": [
      "43 mã villa trong quỹ Sun Feria (sheet tháng 7/2026)",
      "Lọc theo số phòng ngủ — nhiều căn có bể bơi riêng, karaoke, bàn bi-a",
      "Một số villa có thang máy; giá cuối tuần nhiều căn bán theo cặp 2 đêm",
      "Liên hệ DST để nhận ảnh và tư vấn villa phù hợp nhóm"
    ],
    "dataSource": "Google Sheet Villa Sun Feria — export CSV tháng 7/2026",
    "unitCount": 43
  },
  "villa-flc": {
    "unitSamples": [
      {
        "code": "BT9-32",
        "bedrooms": 6,
        "features": [
          "Phòng karaoke, Bàn Bi a. View vịnh, thành phố"
        ],
        "weekdayPrice": "7 triệu/đêm",
        "fridayPrice": "9 triệu/đêm",
        "saturdayPrice": "11 triệu/đêm",
        "sundayPrice": "7 triệu/đêm"
      },
      {
        "code": "BT9-14",
        "bedrooms": 6,
        "features": [
          "Phòng karaoke, Bàn Bi a."
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "8.5 triệu/đêm",
        "saturdayPrice": "10.5 triệu/đêm",
        "sundayPrice": "6.5 triệu/đêm"
      },
      {
        "code": "BT6B-43",
        "bedrooms": 5,
        "features": [
          "Phòng karaoke, View Golf"
        ],
        "weekdayPrice": "6 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "9 triệu/đêm",
        "sundayPrice": "6 triệu/đêm"
      },
      {
        "code": "BT8-6B",
        "bedrooms": 9,
        "features": [
          "Sân vườn rộng 1000 mét, Bể cá Koi"
        ],
        "weekdayPrice": "11.5 triệu/đêm",
        "fridayPrice": "16 triệu/đêm",
        "saturdayPrice": "17.5 triệu/đêm",
        "sundayPrice": "11.5 triệu/đêm"
      },
      {
        "code": "BT3-6A",
        "bedrooms": 5,
        "features": [
          "Sân vườn rộng, View Vịnh"
        ],
        "weekdayPrice": "9.5 triệu/đêm",
        "fridayPrice": "12.5 triệu/đêm",
        "saturdayPrice": "12.5 triệu/đêm",
        "sundayPrice": "9.5 triệu/đêm"
      },
      {
        "code": "BT9-45",
        "bedrooms": 5,
        "features": [
          "Dàn Karaoke, bi a, bi lắc, View vịnh"
        ],
        "weekdayPrice": "5.5tr 2đ -500",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "11(cặp 16)",
        "sundayPrice": "6 triệu/đêm"
      },
      {
        "code": "BT6-33",
        "bedrooms": 5,
        "features": [
          "View nội khu"
        ],
        "weekdayPrice": "5.5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "8 triệu/đêm",
        "sundayPrice": "7 triệu/đêm"
      },
      {
        "code": "BT6-37",
        "bedrooms": 5,
        "features": [
          "View nội khu"
        ],
        "weekdayPrice": "5.5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "8 triệu/đêm",
        "sundayPrice": "7 triệu/đêm"
      },
      {
        "code": "BT6-11",
        "bedrooms": 5,
        "features": [
          "Sân vườn, View nội khu"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "9 triệu/đêm",
        "sundayPrice": "8 triệu/đêm"
      },
      {
        "code": "BT6-10",
        "bedrooms": 5,
        "features": [
          "View nội khu"
        ],
        "weekdayPrice": "6 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "8 triệu/đêm",
        "sundayPrice": "6 triệu/đêm"
      },
      {
        "code": "BT8-15",
        "bedrooms": 5,
        "features": [
          "Vườn rộng, View Vịnh, thành phố."
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "9 triệu/đêm",
        "sundayPrice": "8 triệu/đêm"
      },
      {
        "code": "BT9-03",
        "bedrooms": 5,
        "features": [
          "View nội khu"
        ],
        "weekdayPrice": "6 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "8 triệu/đêm",
        "sundayPrice": "7 triệu/đêm"
      },
      {
        "code": "BT9-25",
        "bedrooms": 5,
        "features": [
          "Phòng karaoke, View nội Khu"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "9 triệu/đêm",
        "sundayPrice": "8 triệu/đêm"
      },
      {
        "code": "BT9-34",
        "bedrooms": 6,
        "features": [
          "Phòng karaoke, View Vịnh, TP, Vườn rộng"
        ],
        "weekdayPrice": "7 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "9.5 triệu/đêm",
        "sundayPrice": "8 triệu/đêm"
      },
      {
        "code": "BT9-46",
        "bedrooms": 6,
        "features": [
          "View Vịnh, Thành Phố"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "9 triệu/đêm",
        "sundayPrice": "8 triệu/đêm"
      },
      {
        "code": "BT9-12A",
        "bedrooms": 6,
        "features": [
          "Phòng karaoke, Bi a View Nội Khu, sân Golf"
        ],
        "weekdayPrice": "7.5 triệu/đêm",
        "fridayPrice": "9.5 triệu/đêm",
        "saturdayPrice": "9.5 triệu/đêm",
        "sundayPrice": "7.5 triệu/đêm"
      },
      {
        "code": "BT6-24",
        "bedrooms": 5,
        "features": [
          "View nội khu"
        ],
        "weekdayPrice": "5.5 triệu/đêm",
        "fridayPrice": "7.5 triệu/đêm",
        "saturdayPrice": "7.5 triệu/đêm",
        "sundayPrice": "5.5 triệu/đêm"
      },
      {
        "code": "BT12-41",
        "bedrooms": 5,
        "features": [
          "Phòng karaoke, vườn rộng, Bi a, View Vịnh"
        ],
        "weekdayPrice": "9 triệu/đêm",
        "fridayPrice": "11 triệu/đêm",
        "saturdayPrice": "11 triệu/đêm",
        "sundayPrice": "9 triệu/đêm"
      },
      {
        "code": "BT12-44",
        "bedrooms": 5,
        "features": [
          "View vịnh, sân vườn, phòng karaoke"
        ],
        "weekdayPrice": "7 triệu/đêm",
        "fridayPrice": "9 triệu/đêm",
        "saturdayPrice": "9 triệu/đêm",
        "sundayPrice": "7 triệu/đêm"
      },
      {
        "code": "BT6B-08",
        "bedrooms": 4,
        "features": [
          "Phòng karaoke, Sân vườn rộng, View golf"
        ],
        "weekdayPrice": "5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "7 triệu/đêm",
        "sundayPrice": "5 triệu/đêm"
      },
      {
        "code": "BT6b-6B",
        "bedrooms": 5,
        "features": [
          "Sân vườn rộng, View Golf"
        ],
        "weekdayPrice": "5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "7 triệu/đêm",
        "sundayPrice": "5 triệu/đêm"
      },
      {
        "code": "BT12-29",
        "bedrooms": 4,
        "features": [
          "Bàn Bi a mini, Bi lắc"
        ],
        "weekdayPrice": "6 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "8 triệu/đêm",
        "sundayPrice": "6 triệu/đêm"
      },
      {
        "code": "BT12-30",
        "bedrooms": 5,
        "features": [
          "Hướng vịnh"
        ],
        "weekdayPrice": "4.5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "7 triệu/đêm",
        "sundayPrice": "4.5 triệu/đêm"
      },
      {
        "code": "BT2-19",
        "bedrooms": 5,
        "features": [
          "Sân vườn, dàn Karaoke"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "7.5 triệu/đêm",
        "sundayPrice": "6.5 triệu/đêm"
      },
      {
        "code": "BT3-12A",
        "bedrooms": 4,
        "features": [
          "View nội khu"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "7.5 triệu/đêm",
        "sundayPrice": "6.5 triệu/đêm"
      },
      {
        "code": "BT6B-6A",
        "bedrooms": 5,
        "features": [
          "Sân vườn rộng, View Golf"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "7.5 triệu/đêm",
        "sundayPrice": "6.5 triệu/đêm"
      },
      {
        "code": "BT6B-19",
        "bedrooms": 5,
        "features": [
          "Sân vườn rộng,View Vịnh"
        ],
        "weekdayPrice": "7.5 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "8.5 triệu/đêm",
        "sundayPrice": "7.5 triệu/đêm"
      },
      {
        "code": "BT6-25",
        "bedrooms": 5,
        "features": [
          "View nội khu"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "7 triệu/đêm",
        "saturdayPrice": "7.5 triệu/đêm",
        "sundayPrice": "6.5 triệu/đêm"
      },
      {
        "code": "BT8-6A",
        "bedrooms": 5,
        "features": [
          "Sân vườn rộng, View Vịnh"
        ],
        "weekdayPrice": "7.5 triệu/đêm",
        "fridayPrice": "9 triệu/đêm",
        "saturdayPrice": "9.5 triệu/đêm",
        "sundayPrice": "7.5 triệu/đêm"
      },
      {
        "code": "BT12-03",
        "bedrooms": 7,
        "features": [
          "Vườn rộng, View Golf"
        ],
        "weekdayPrice": "8.5 triệu/đêm",
        "fridayPrice": "9 triệu/đêm",
        "saturdayPrice": "9.5 triệu/đêm",
        "sundayPrice": "8.5 triệu/đêm"
      },
      {
        "code": "BT12-25",
        "bedrooms": 7,
        "features": [
          "Phòng karaoke, View nội khu"
        ],
        "weekdayPrice": "8.5 triệu/đêm",
        "fridayPrice": "9 triệu/đêm",
        "saturdayPrice": "9.5 triệu/đêm",
        "sundayPrice": "8.5 triệu/đêm"
      },
      {
        "code": "BT12-40",
        "bedrooms": 5,
        "features": [
          "Phòng karaoke, sân vườn rộng, cầu trượt, View Vịnh, Bi a"
        ],
        "weekdayPrice": "9 triệu/đêm",
        "fridayPrice": "11 triệu/đêm",
        "saturdayPrice": "11 triệu/đêm",
        "sundayPrice": "9 triệu/đêm"
      },
      {
        "code": "BT3-01",
        "bedrooms": 5,
        "features": [
          "Hướng vịnh"
        ],
        "weekdayPrice": "5.5 triệu/đêm",
        "fridayPrice": "8 triệu/đêm",
        "saturdayPrice": "9.5 triệu/đêm",
        "sundayPrice": "5.5 triệu/đêm"
      },
      {
        "code": "BT3-24",
        "bedrooms": 6,
        "features": [
          "Hướng vịnh"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "8.5 triệu/đêm",
        "saturdayPrice": "10.5 triệu/đêm",
        "sundayPrice": "6.5 triệu/đêm"
      },
      {
        "code": "BT3-28",
        "bedrooms": 5,
        "features": [
          "View vịnh"
        ],
        "weekdayPrice": "5.5 triệu/đêm",
        "fridayPrice": "7.5 triệu/đêm",
        "saturdayPrice": "9 triệu/đêm",
        "sundayPrice": "5.5 triệu/đêm"
      },
      {
        "code": "BT9-39B",
        "bedrooms": 7,
        "features": [
          "View khách sạn FLC"
        ],
        "weekdayPrice": "6.5 triệu/đêm",
        "fridayPrice": "9 triệu/đêm",
        "saturdayPrice": "10 triệu/đêm",
        "sundayPrice": "6.5 triệu/đêm"
      }
    ],
    "priceSummary": [
      {
        "label": "4 PN",
        "weekday": "Từ 5–6.5 triệu/đêm",
        "friday": "Từ 7–8 triệu/đêm",
        "saturday": "Từ 7–8 triệu/đêm",
        "sunday": "Từ 5–6.5 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa FLC"
      },
      {
        "label": "5 PN",
        "weekday": "Từ 4.5–9.5 triệu/đêm",
        "friday": "Từ 7–12.5 triệu/đêm",
        "saturday": "Từ 7–12.5 triệu/đêm",
        "sunday": "Từ 4.5–9.5 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa FLC"
      },
      {
        "label": "6 PN",
        "weekday": "Từ 6.5–7.5 triệu/đêm",
        "friday": "Từ 8–9.5 triệu/đêm",
        "saturday": "Từ 9–11 triệu/đêm",
        "sunday": "Từ 6.5–8 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa FLC"
      },
      {
        "label": "7 PN",
        "weekday": "Từ 6.5–8.5 triệu/đêm",
        "friday": "Từ 9 triệu/đêm",
        "saturday": "Từ 9.5–10 triệu/đêm",
        "sunday": "Từ 6.5–8.5 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa FLC"
      },
      {
        "label": "9 PN",
        "weekday": "Từ 11.5 triệu/đêm",
        "friday": "Từ 16 triệu/đêm",
        "saturday": "Từ 17.5 triệu/đêm",
        "sunday": "Từ 11.5 triệu/đêm",
        "note": "Giá tham khảo từ sheet Villa FLC"
      }
    ],
    "amenities": [
      "Phòng karaoke",
      "Bàn Bi a. View vịnh",
      "thành phố",
      "Bàn Bi a.",
      "View Golf",
      "Sân vườn rộng 1000 mét",
      "Bể cá Koi",
      "Sân vườn rộng",
      "View Vịnh",
      "Dàn Karaoke",
      "bi a",
      "bi lắc"
    ],
    "highlights": [
      "36 mã villa FLC Hạ Long (sheet tháng 07/2026)",
      "View vịnh, view golf, karaoke, bi-a, sân vườn theo từng mã căn",
      "Giá T6/T7/CN cập nhật riêng — nhiều căn cuối tuần bán cặp",
      "Liên hệ DST để check giá và lịch trống theo ngày"
    ],
    "dataSource": "Google Sheet Villa FLC — export CSV tháng 07/2026",
    "unitCount": 36
  }
};
